POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Jane Doe",
  "number": "12345678"
}

### error content missing
POST http://localhost:3001/api/persons
Content-Type: application/json

{

}