POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjYzMWNjNTY1MTI0NTgzOTBkODEzMzg1OCIsImlhdCI6MTY2MjgzMTI4MH0.b9VEiCG9wXgoPjV8y5o7vCcKkGGF8Zm8IFfKw0CE84k

{
  "title": "My third blog",
  "author": "John Doe",
  "url": "http://example.com",
  "userId": "631cc56512458390d8133858"
}

###
POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjYzMWNjNTY1MTI0NTgzOTBkODEzMzg1OCIsImlhdCI6MTY2MjgzMTI4MH0.b9VEiCG9wXgoPjV8y5o7vCcKkGGF8Zm8IFfKw0CE84k

{
  "title": "My second blog",
  "author": "Jane Doe",
  "url": "https://readerofpanemblog.wordpress.com",
  "likes": 5,
  "userId": "631cc56512458390d8133858"
}

###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "My third blog",
  "author": "John Doe",
  "url": "another-example.com",
  "likes": 10

}