DELETE http://localhost:3003/api/blogs/631ccea392028fafb300fb55
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjYzMWNjNTY1MTI0NTgzOTBkODEzMzg1OCIsImlhdCI6MTY2MjgzMTI4MH0.b9VEiCG9wXgoPjV8y5o7vCcKkGGF8Zm8IFfKw0CE84k


###
DELETE http://localhost:3003/api/blogs/631ccea792028fafb300fb59
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiaWQiOiI2MzFjZDA0ZTlkZTBhZWJiYjY3ZTEyZDQiLCJpYXQiOjE2NjI4MzI3ODl9.w2kS4chEM6xOzZoF619TLdXH_FHHhCHILtP2JXXz-so

###
DELETE http://localhost:3003/api/blogs/631ccea792028fafb310fb59
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiaWQiOiI2MzFjZDA0ZTlkZTBhZWJiYjY3ZTEyZDQiLCJpYXQiOjE2NjI4MzI3ODl9.w2kS4chEM6xOzZoF619TLdXH_FHHhCHILtP2JXXz-so


###
DELETE http://localhost:3003/api/blogs/63b591263c5401e8ba1d2f56
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiaWQiOiI2MzFjZDA0ZTlkZTBhZWJiYjY3ZTEyZDQiLCJpYXQiOjE2NjI4MzI3ODl9.w2kS4chEM6xOzZoF619TLdXH_FHHhCHILtP2JXXz-so